name: Waka Readme

on:
  schedule:
    - cron: '0 16 * * *' # 每天 UTC 时间 16:00 (北京时间 00:00) 运行
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "zh" # 设置为中文
